name: Science Parse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 'adopt@1.11'

    - name: Cache Ivy
      uses: actions/cache@v2
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-ivy-

    - name: Cache Coursier
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-coursier-

    - name: Add AllenAI Maven repository
      run: |
        echo "resolvers += \"AllenAI Maven\" at \"https://dl.bintray.com/allenai/maven\"" >> build.sbt

    - name: Build and test
      run: sbt test
